repos:
- repo: https://github.com/nix-community/nixpkgs-fmt
  rev: master
  hooks:
  - id: nixpkgs-fmt
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0  # Use the ref you want to point at
  hooks:
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: end-of-file-fixer
